# Generated by Django 5.1.5 on 2025-01-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='achete',
        ),
    ]
