# Generated by Django 5.1.5 on 2025-01-22 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_article_nom_alter_article_quantite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='utilisateur',
        ),
    ]
